### PR TITLE
Add pHYs handling in Reader and Writer classes

### PR DESCRIPTION
**Pull request by ohtrebal**
Hello
I needed pHYs to create data with different x and y resolutions (sonar images).

Alain

### CODE REVIEW

**Comment by drj11** [comment]
I like this in principal. I think I'd like it even more if there was only one new parameter to the already ridiculous constructor for the `Writer` class.

A test that included a `pHYs` chunk would definitely ease the passage of this pull request. :)

**Comment by ohtrebal** [comment]
Do you mean that a tuple (x_pixel_per_unit, y_pixel_per_unit, unit_is_meter) would be ok as a single parameter?
I'll prepare a test for pHYs chunk...

**Comment by drj11** [comment]
yes, I was thinking

```
Writer(blah blah blah, phys=(xppu, yppu, ismetre))
```

**Comment by ohtrebal** [comment]
It is also possible to have:

**Comment by drj11** [comment]
There's a bigger discussion as to how to introduce arbitrary new chunks. We haven't thought about that much, so just do whatever you feel is tasteful.

**Comment by ohtrebal** [comment]
Ok.
I was also thinking of the tIME chunk, that may be useful to me... So, the second way may be better...
I'm not used to git and github, if I commit new code (for pHYs and tIME), is it possible to merge it to this pull request? Or would you prefer a new pull request?
Is the discussion about arbitrary chunk visible on the net? I'm intersted in following it...
I may be busy next days, I think I'll code and propose tests at the end of the week.
Thanks.

**Comment by drj11** [comment]
I merged. Now you're new code can go in a new pull request. :)

**Pull request merged**
