### PR TITLE
Debianisation

### PR DESCRIPTION
**Pull request by shtrom**
This adds metadata to create a Debian package.

### CODE REVIEW

**Comment by drj11** [comment]
I'm quite conflicted about this change. It's cool that pypng can be packaged for a particular operating system, but I don't really like the idea of polluting the repo with this very OS-specific stuff.

I'm not really familiar with Debian; is it usual for the debian files to be maintained in the upstream source?

**Comment by shtrom** [comment]
Actually, I think Debian prefers separate packaging code, but it was easier for me to offer it upstream.

**Comment by drj11** [comment]
Was thinking about rejecting this as not very interested in leaving debian packaging stuff around.

Then I saw the license change. Rejected.

**Comment by shtrom** [comment]
Sure, no worries.

Though, did I get the license wrong (MIT)? Or is this for the packaging code (GPL2)?

**Comment by drj11** [comment]
Ah, wait, I think _I'm_ confused about the license.

(this is well off topic for this issue by the way)

what does the `debian/copyright` file cover? Just the Debian packaging files?

**Comment by shtrom** [comment]
(Well, the issue's closed anyway (: )

The debian/copyright files describes the license(s) of both the upstream code and the packaging code. It uses shell-like globs in the `FIles` field to indicate which files are covered by which license. In this case, the packaging code (`debian/*`) is GPLv2, but it also states that the rest (`*`) is MIT.

**Comment by drj11** [comment]
ah, thanks for the schooling me. And yes, that sounds like the right license situation. :)

**Pull request closed without merging**
